### ISSUE TITLE
The most useful Markdown table plugin

### ISSUE THREAD

**Issue by kdurant** [SCJangra/table-nvim#3]
Nothing else. Just want to thank you.

**Comment by SCJangra** [comment]
Glad you like it.

**Comment by tahir-hassan** [comment]
Honestly, this is an awesome plugin.  I picked this plugin randomly and even without much experience with NeoVim (I use LunarVim), it works flawlessly.

**Comment by SCJangra** [comment]
@tahir-hassan Thank you, I appreciate it.
